name: 'Hello Action'
description: 'This action prints a greeting message.'
inputs:
  name:
    description: 'Name to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Greet
      run: |
        echo "Hello ${{ inputs.name }}!"
      shell: bash  # Specify the shell environment here
