name: 'Add Comment with Personalized Message'
description: 'This action adds a comment with a personalized message.'
inputs:
  name:
    description: 'Name to personalize the message'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current time
      id: current-time
      run: |
        echo "::set-output name=current_time::$(date +"%H:%M:%S")"

    - name: Add Comment
      if: success()
      run: |
        NAME="${{ inputs.name }}"
        TIME="${{ steps.current-time.outputs.current_time }}"
        COMMENT="Hello $NAME at $TIME!"
        COMMENTS_URL="${{ github.event.pull_request.comments_url }}"
        AUTH_HEADER="Authorization: token ${{ github.token }}"
        curl -sS -X POST -H "Content-Type: application/json" -H "$AUTH_HEADER" -d "{\"body\":\"$COMMENT\"}" $COMMENTS_URL
