name: Hello Workflow

on: [push]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Action
        uses: tiriana/add-jira-link-to-pr@RADEK-234-test
        with:
          name: "Radek"  # Replace with the name you want to greet
